Repository cossacklabs/openssl-apple, pull requests merged in 2020-11, with the labels that each got.

#17 Merge branch 'master' into cossacklabs
  .gitignore
  .travis.yml
  Demo.xcodeproj/project.pbxproj
  Demo.xcworkspace/contents.xcworkspacedata
  Demo/AppDelegate.swift
  Demo/Assets.xcassets/AccentColor.colorset/Contents.json
  Demo/Assets.xcassets/AppIcon.appiconset/Contents.json
  Demo/Assets.xcassets/Contents.json
  Demo/Base.lproj/LaunchScreen.storyboard
  Demo/Base.lproj/Main.storyboard
  Demo/Info.plist
  Demo/SceneDelegate.swift
  Demo/ViewController.swift
  DemoTests/DemoTests.swift
  DemoTests/Info.plist
  Gemfile.lock
  OpenSSL-Apple.podspec
  Podfile
  Podfile.lock
  README.md
  assets/AppleTVOS
  assets/AppleTVSimulator
  assets/Catalyst/Info.plist
  assets/Watch/Info.plist
  assets/WatchOS
  assets/WatchSimulator
  assets/iPhoneOS
  assets/iPhoneSimulator
  build-libssl.sh
  config/20-all-platforms.conf
  create-openssl-framework.sh
  scripts/build-loop-archs.sh
  scripts/build-loop-targets.sh
Labels: upstream

#19 Revert "Merge branch 'master' into cossacklabs"
  .gitignore
  .travis.yml
  Demo.xcodeproj/project.pbxproj
  Demo.xcworkspace/contents.xcworkspacedata
  Demo/AppDelegate.swift
  Demo/Assets.xcassets/AccentColor.colorset/Contents.json
  Demo/Assets.xcassets/AppIcon.appiconset/Contents.json
  Demo/Assets.xcassets/Contents.json
  Demo/Base.lproj/LaunchScreen.storyboard
  Demo/Base.lproj/Main.storyboard
  Demo/Info.plist
  Demo/SceneDelegate.swift
  Demo/ViewController.swift
  DemoTests/DemoTests.swift
  DemoTests/Info.plist
  Gemfile.lock
  OpenSSL-Apple.podspec.template
  Podfile
  Podfile.lock
  README.md
  assets/AppleTVOS
  assets/AppleTVSimulator
  assets/Catalyst/Info.plist
  assets/WatchOS
  assets/WatchOS/Info.plist
  assets/WatchSimulator
  assets/iPhoneOS
  assets/iPhoneSimulator
  build-libssl.sh
  config/20-all-platforms.conf
  create-openssl-framework.sh
  scripts/build-loop-archs.sh
  scripts/build-loop-targets.sh
Labels: upstream

#18 Remove arm64e slice; return dyn linking for CocoaPods
  Makefile
  cocoapods/CLOpenSSL.podspec.template
  config/20-all-platforms.conf
  create-openssl-framework.sh
  scripts/update-specs.sh
Labels: Apple Silicon

#20 Merge branch 'master' into cossacklabs, again
  .gitignore
  .travis.yml
  Demo.xcodeproj/project.pbxproj
  Demo.xcworkspace/contents.xcworkspacedata
  Demo/AppDelegate.swift
  Demo/Assets.xcassets/AccentColor.colorset/Contents.json
  Demo/Assets.xcassets/AppIcon.appiconset/Contents.json
  Demo/Assets.xcassets/Contents.json
  Demo/Base.lproj/LaunchScreen.storyboard
  Demo/Base.lproj/Main.storyboard
  Demo/Info.plist
  Demo/SceneDelegate.swift
  Demo/ViewController.swift
  DemoTests/DemoTests.swift
  DemoTests/Info.plist
  Gemfile.lock
  OpenSSL-Apple.podspec
  Podfile
  Podfile.lock
  README.md
  assets/AppleTVOS
  assets/AppleTVSimulator
  assets/Catalyst/Info.plist
  assets/Watch/Info.plist
  assets/WatchOS
  assets/WatchSimulator
  assets/iPhoneOS
  assets/iPhoneSimulator
  build-libssl.sh
  config/20-all-platforms.conf
  create-openssl-framework.sh
  scripts/build-loop-archs.sh
  scripts/build-loop-targets.sh
Labels: Apple Silicon, XCFramework, upstream

#21 XCFramework support and packaging
  Makefile
  build-libssl.sh
  cocoapods/CLOpenSSL.podspec.template
  config/20-all-platforms.conf
  scripts/create-packages.sh
  scripts/update-specs.sh
Labels: XCFramework, carthage, cocoapods
